import io from 'socket.io-client';

export interface DataSource {
  id: string;
  type: 'pdf' | 'news' | 'blog' | 'research' | 'api' | 'web';
  title: string;
  url?: string;
  content: string;
  lastUpdated: Date;
  metadata?: any;
  relevanceScore?: number;
}

export interface DataUpdate {
  sourceId: string;
  changeType: 'added' | 'updated' | 'removed';
  newContent?: string;
  timestamp: Date;
}

export class PathwayService {
  private socket: any;
  private dataSources: Map<string, DataSource> = new Map();
  private updateCallbacks: Set<(update: DataUpdate) => void> = new Set();
  private connectionRetries = 0;
  private maxRetries = 5;

  constructor() {
    this.initializeMockData();
    this.connectWebSocket();
    this.startMockUpdates();
  }

  private initializeMockData() {
    const mockSources: DataSource[] = [
      {
        id: 'pdf-1',
        type: 'pdf',
        title: 'AI Research Paper 2024',
        content: 'Recent advances in artificial intelligence show promising developments in natural language processing and machine learning algorithms...',
        lastUpdated: new Date(),
        metadata: { pages: 25, author: 'Dr. Smith' }
      },
      {
        id: 'news-1',
        type: 'news',
        title: 'Tech Industry Update',
        url: 'https://example.com/tech-news',
        content: 'The technology sector continues to evolve with new innovations in AI, blockchain, and quantum computing...',
        lastUpdated: new Date(),
        metadata: { source: 'TechNews Daily' }
      },
      {
        id: 'blog-1',
        type: 'blog',
        title: 'Machine Learning Best Practices',
        url: 'https://example.com/ml-blog',
        content: 'Best practices for implementing machine learning models in production environments include proper data validation...',
        lastUpdated: new Date(),
        metadata: { author: 'Jane Doe', readTime: '8 min' }
      }
    ];

    mockSources.forEach(source => {
      this.dataSources.set(source.id, source);
    });
  }

  private connectWebSocket() {
    const wsUrl = import.meta.env.VITE_PATHWAY_WEBSOCKET_URL || 'ws://localhost:3001';
    
    try {
      this.socket = io(wsUrl, {
        transports: ['websocket'],
        timeout: 5000
      });

      this.socket.on('connect', () => {
        console.log('Connected to Pathway WebSocket');
        this.connectionRetries = 0;
      });

      this.socket.on('data_update', (update: DataUpdate) => {
        this.handleDataUpdate(update);
      });

      this.socket.on('connect_error', (error: any) => {
        console.log('Pathway WebSocket connection failed, using mock data:', error.message);
        this.handleConnectionError();
      });

      this.socket.on('disconnect', () => {
        console.log('Pathway WebSocket disconnected');
        this.handleDisconnection();
      });

    } catch (error) {
      console.log('WebSocket not available, using mock real-time updates');
      this.handleConnectionError();
    }
  }

  private handleConnectionError() {
    if (this.connectionRetries < this.maxRetries) {
      this.connectionRetries++;
      setTimeout(() => {
        console.log(`Retrying Pathway connection (${this.connectionRetries}/${this.maxRetries})`);
        this.connectWebSocket();
      }, 5000);
    }
  }

  private handleDisconnection() {
    setTimeout(() => {
      this.connectWebSocket();
    }, 3000);
  }

  private startMockUpdates() {
    console.log('📡 Starting mock real-time updates...');
    
    // Simulate real-time updates every 15 seconds for demo
    setInterval(() => {
      this.simulateDataUpdate();
    }, 15000);

    // Simulate new data source every 45 seconds for demo
    setInterval(() => {
      this.simulateNewDataSource();
    }, 45000);
    
    // Immediate demo update after 5 seconds
    setTimeout(() => {
      this.simulateNewDataSource();
    }, 5000);
  }

  private simulateDataUpdate() {
    const sources = Array.from(this.dataSources.values());
    if (sources.length === 0) return;

    const randomSource = sources[Math.floor(Math.random() * sources.length)];
    const updatedContent = this.generateUpdatedContent(randomSource);

    const update: DataUpdate = {
      sourceId: randomSource.id,
      changeType: 'updated',
      newContent: updatedContent,
      timestamp: new Date()
    };

    this.handleDataUpdate(update);
  }

  private simulateNewDataSource() {
    const newSource: DataSource = {
      id: `auto-${Date.now()}`,
      type: Math.random() > 0.5 ? 'news' : 'blog',
      title: `Breaking: New Development in AI Research ${new Date().toLocaleDateString()}`,
      content: `Latest research indicates significant breakthroughs in AI capabilities. This update was automatically ingested at ${new Date().toLocaleTimeString()}.`,
      lastUpdated: new Date(),
      metadata: { autoGenerated: true }
    };

    this.dataSources.set(newSource.id, newSource);

    const update: DataUpdate = {
      sourceId: newSource.id,
      changeType: 'added',
      newContent: newSource.content,
      timestamp: new Date()
    };

    this.notifyUpdateCallbacks(update);
  }

  private generateUpdatedContent(source: DataSource): string {
    const updates = [
      ' [UPDATE] New findings suggest enhanced performance metrics.',
      ' [BREAKING] Industry experts weigh in on latest developments.',
      ' [ANALYSIS] Recent data shows significant improvements.',
      ' [RESEARCH] Additional studies confirm previous hypotheses.'
    ];

    const randomUpdate = updates[Math.floor(Math.random() * updates.length)];
    return source.content + randomUpdate;
  }

  private handleDataUpdate(update: DataUpdate) {
    const source = this.dataSources.get(update.sourceId);
    
    if (source && update.newContent) {
      source.content = update.newContent;
      source.lastUpdated = update.timestamp;
      this.dataSources.set(update.sourceId, source);
    }

    this.notifyUpdateCallbacks(update);
  }

  private notifyUpdateCallbacks(update: DataUpdate) {
    this.updateCallbacks.forEach(callback => {
      try {
        callback(update);
      } catch (error) {
        console.error('Error in update callback:', error);
      }
    });
  }

  // Public API methods
  getAllDataSources(): DataSource[] {
    return Array.from(this.dataSources.values()).sort(
      (a, b) => b.lastUpdated.getTime() - a.lastUpdated.getTime()
    );
  }

  getDataSourceById(id: string): DataSource | undefined {
    return this.dataSources.get(id);
  }

  searchDataSources(query: string): DataSource[] {
    const lowerQuery = query.toLowerCase();
    return this.getAllDataSources().filter(source =>
      source.title.toLowerCase().includes(lowerQuery) ||
      source.content.toLowerCase().includes(lowerQuery)
    );
  }

  onDataUpdate(callback: (update: DataUpdate) => void): () => void {
    this.updateCallbacks.add(callback);
    
    return () => {
      this.updateCallbacks.delete(callback);
    };
  }

  getRealtimeMetrics() {
    const sources = this.getAllDataSources();
    const now = new Date();
    const hourAgo = new Date(now.getTime() - 60 * 60 * 1000);
    
    const recentUpdates = sources.filter(s => s.lastUpdated > hourAgo);
    
    return {
      totalSources: sources.length,
      recentUpdates: recentUpdates.length,
      sourceTypes: this.getSourceTypeBreakdown(),
      lastUpdateTime: sources.length > 0 ? sources[0].lastUpdated : null,
      avgUpdateFrequency: this.calculateUpdateFrequency()
    };
  }

  private getSourceTypeBreakdown() {
    const breakdown: Record<string, number> = {};
    
    this.dataSources.forEach(source => {
      breakdown[source.type] = (breakdown[source.type] || 0) + 1;
    });
    
    return breakdown;
  }

  private calculateUpdateFrequency(): number {
    const sources = this.getAllDataSources();
    if (sources.length === 0) return 0;

    const now = new Date();
    const dayAgo = new Date(now.getTime() - 24 * 60 * 60 * 1000);
    
    const dailyUpdates = sources.filter(s => s.lastUpdated > dayAgo);
    return dailyUpdates.length;
  }

  // Force refresh data sources (for demo purposes)
  async refreshAllSources(): Promise<void> {
    console.log('Refreshing all data sources...');
    
    this.dataSources.forEach(source => {
      source.lastUpdated = new Date();
      source.content += ' [REFRESHED]';
    });

    // Notify about batch update
    const batchUpdate: DataUpdate = {
      sourceId: 'all',
      changeType: 'updated',
      timestamp: new Date()
    };
    
    this.notifyUpdateCallbacks(batchUpdate);
  }

  disconnect() {
    if (this.socket) {
      this.socket.disconnect();
    }
  }
}

export const pathwayService = new PathwayService();