// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zayfxclzkdgxnyowzjbl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpheWZ4Y2x6a2RneG55b3d6amJsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg5NTM2ODUsImV4cCI6MjA3NDUyOTY4NX0.kH-hmIRbnMwAuoamhEZpMGBbuoGWh_NW9LlCYT47ijI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});